[package]
name = "trait_query_test"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_unofficial_trait_queries = { path = "../bevy_unofficial_trait_queries" }
bevy = { path = "../../bevy" }
